# Generated by Django 3.1.7 on 2021-05-12 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210414_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 16, 39, 22, 585668, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='920a22f30ad5c769f130813896f1a16388d027f3690c760d87125cb80a06406f', max_length=64),
        ),
    ]
