# Generated by Django 3.1.7 on 2021-05-12 18:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210512_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 18, 31, 39, 834684, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='af0f83344789e6a3d557fb9945e27a100db178e7ff84ca0deda20ff0c4adf385', max_length=64),
        ),
    ]
