# Generated by Django 3.1.7 on 2021-05-12 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'pizza', 'verbose_name_plural': 'pizza'},
        ),
        migrations.AlterModelOptions(
            name='storeingredients',
            options={'verbose_name': 'store ingredient', 'verbose_name_plural': 'store ingredients'},
        ),
        migrations.AlterField(
            model_name='storeingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='stores.ingredient'),
        ),
    ]
